version: '3'

services:
  postgres:
    build:
      context: ./sql
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: sql@sql
    ports:
      - "5432:5432"
    container_name: postgres_instance

  taxi:
    build:
      context: ./taxi
      dockerfile: Dockerfile
    ports:
      - "9990:9990"
    container_name: taxi_instance

  
  medic:
    build:
      context: ./medic
      dockerfile: Dockerfile
    ports:
      - "9991:9991"
    container_name: medic_instance

  
  kitmas:
    build:
      context: ./KitchenMaster
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
    container_name: kitmas_instance

  